//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortGroup) DeepCopyInto(out *PortGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortGroup.
func (in *PortGroup) DeepCopy() *PortGroup {
	if in == nil {
		return nil
	}
	out := new(PortGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PortGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortGroupList) DeepCopyInto(out *PortGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PortGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortGroupList.
func (in *PortGroupList) DeepCopy() *PortGroupList {
	if in == nil {
		return nil
	}
	out := new(PortGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PortGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortGroupObservation) DeepCopyInto(out *PortGroupObservation) {
	*out = *in
	if in.ConfigVersion != nil {
		in, out := &in.ConfigVersion, &out.ConfigVersion
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortGroupObservation.
func (in *PortGroupObservation) DeepCopy() *PortGroupObservation {
	if in == nil {
		return nil
	}
	out := new(PortGroupObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortGroupParameters) DeepCopyInto(out *PortGroupParameters) {
	*out = *in
	if in.ActiveUplinks != nil {
		in, out := &in.ActiveUplinks, &out.ActiveUplinks
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.AllowForgedTransmits != nil {
		in, out := &in.AllowForgedTransmits, &out.AllowForgedTransmits
		*out = new(bool)
		**out = **in
	}
	if in.AllowMacChanges != nil {
		in, out := &in.AllowMacChanges, &out.AllowMacChanges
		*out = new(bool)
		**out = **in
	}
	if in.AllowPromiscuous != nil {
		in, out := &in.AllowPromiscuous, &out.AllowPromiscuous
		*out = new(bool)
		**out = **in
	}
	if in.AutoExpand != nil {
		in, out := &in.AutoExpand, &out.AutoExpand
		*out = new(bool)
		**out = **in
	}
	if in.BlockAllPorts != nil {
		in, out := &in.BlockAllPorts, &out.BlockAllPorts
		*out = new(bool)
		**out = **in
	}
	if in.BlockOverrideAllowed != nil {
		in, out := &in.BlockOverrideAllowed, &out.BlockOverrideAllowed
		*out = new(bool)
		**out = **in
	}
	if in.CheckBeacon != nil {
		in, out := &in.CheckBeacon, &out.CheckBeacon
		*out = new(bool)
		**out = **in
	}
	if in.CustomAttributes != nil {
		in, out := &in.CustomAttributes, &out.CustomAttributes
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DirectpathGen2Allowed != nil {
		in, out := &in.DirectpathGen2Allowed, &out.DirectpathGen2Allowed
		*out = new(bool)
		**out = **in
	}
	if in.DistributedVirtualSwitchUUID != nil {
		in, out := &in.DistributedVirtualSwitchUUID, &out.DistributedVirtualSwitchUUID
		*out = new(string)
		**out = **in
	}
	if in.EgressShapingAverageBandwidth != nil {
		in, out := &in.EgressShapingAverageBandwidth, &out.EgressShapingAverageBandwidth
		*out = new(float64)
		**out = **in
	}
	if in.EgressShapingBurstSize != nil {
		in, out := &in.EgressShapingBurstSize, &out.EgressShapingBurstSize
		*out = new(float64)
		**out = **in
	}
	if in.EgressShapingEnabled != nil {
		in, out := &in.EgressShapingEnabled, &out.EgressShapingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.EgressShapingPeakBandwidth != nil {
		in, out := &in.EgressShapingPeakBandwidth, &out.EgressShapingPeakBandwidth
		*out = new(float64)
		**out = **in
	}
	if in.Failback != nil {
		in, out := &in.Failback, &out.Failback
		*out = new(bool)
		**out = **in
	}
	if in.IngressShapingAverageBandwidth != nil {
		in, out := &in.IngressShapingAverageBandwidth, &out.IngressShapingAverageBandwidth
		*out = new(float64)
		**out = **in
	}
	if in.IngressShapingBurstSize != nil {
		in, out := &in.IngressShapingBurstSize, &out.IngressShapingBurstSize
		*out = new(float64)
		**out = **in
	}
	if in.IngressShapingEnabled != nil {
		in, out := &in.IngressShapingEnabled, &out.IngressShapingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IngressShapingPeakBandwidth != nil {
		in, out := &in.IngressShapingPeakBandwidth, &out.IngressShapingPeakBandwidth
		*out = new(float64)
		**out = **in
	}
	if in.LacpEnabled != nil {
		in, out := &in.LacpEnabled, &out.LacpEnabled
		*out = new(bool)
		**out = **in
	}
	if in.LacpMode != nil {
		in, out := &in.LacpMode, &out.LacpMode
		*out = new(string)
		**out = **in
	}
	if in.LivePortMovingAllowed != nil {
		in, out := &in.LivePortMovingAllowed, &out.LivePortMovingAllowed
		*out = new(bool)
		**out = **in
	}
	if in.NetflowEnabled != nil {
		in, out := &in.NetflowEnabled, &out.NetflowEnabled
		*out = new(bool)
		**out = **in
	}
	if in.NetflowOverrideAllowed != nil {
		in, out := &in.NetflowOverrideAllowed, &out.NetflowOverrideAllowed
		*out = new(bool)
		**out = **in
	}
	if in.NetworkResourcePoolKey != nil {
		in, out := &in.NetworkResourcePoolKey, &out.NetworkResourcePoolKey
		*out = new(string)
		**out = **in
	}
	if in.NetworkResourcePoolOverrideAllowed != nil {
		in, out := &in.NetworkResourcePoolOverrideAllowed, &out.NetworkResourcePoolOverrideAllowed
		*out = new(bool)
		**out = **in
	}
	if in.NotifySwitches != nil {
		in, out := &in.NotifySwitches, &out.NotifySwitches
		*out = new(bool)
		**out = **in
	}
	if in.NumberOfPorts != nil {
		in, out := &in.NumberOfPorts, &out.NumberOfPorts
		*out = new(float64)
		**out = **in
	}
	if in.PortConfigResetAtDisconnect != nil {
		in, out := &in.PortConfigResetAtDisconnect, &out.PortConfigResetAtDisconnect
		*out = new(bool)
		**out = **in
	}
	if in.PortNameFormat != nil {
		in, out := &in.PortNameFormat, &out.PortNameFormat
		*out = new(string)
		**out = **in
	}
	if in.PortPrivateSecondaryVlanID != nil {
		in, out := &in.PortPrivateSecondaryVlanID, &out.PortPrivateSecondaryVlanID
		*out = new(float64)
		**out = **in
	}
	if in.SecurityPolicyOverrideAllowed != nil {
		in, out := &in.SecurityPolicyOverrideAllowed, &out.SecurityPolicyOverrideAllowed
		*out = new(bool)
		**out = **in
	}
	if in.ShapingOverrideAllowed != nil {
		in, out := &in.ShapingOverrideAllowed, &out.ShapingOverrideAllowed
		*out = new(bool)
		**out = **in
	}
	if in.StandbyUplinks != nil {
		in, out := &in.StandbyUplinks, &out.StandbyUplinks
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.TeamingPolicy != nil {
		in, out := &in.TeamingPolicy, &out.TeamingPolicy
		*out = new(string)
		**out = **in
	}
	if in.TrafficFilterOverrideAllowed != nil {
		in, out := &in.TrafficFilterOverrideAllowed, &out.TrafficFilterOverrideAllowed
		*out = new(bool)
		**out = **in
	}
	if in.TxUplink != nil {
		in, out := &in.TxUplink, &out.TxUplink
		*out = new(bool)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.UplinkTeamingOverrideAllowed != nil {
		in, out := &in.UplinkTeamingOverrideAllowed, &out.UplinkTeamingOverrideAllowed
		*out = new(bool)
		**out = **in
	}
	if in.VlanID != nil {
		in, out := &in.VlanID, &out.VlanID
		*out = new(float64)
		**out = **in
	}
	if in.VlanOverrideAllowed != nil {
		in, out := &in.VlanOverrideAllowed, &out.VlanOverrideAllowed
		*out = new(bool)
		**out = **in
	}
	if in.VlanRange != nil {
		in, out := &in.VlanRange, &out.VlanRange
		*out = make([]VlanRangeParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortGroupParameters.
func (in *PortGroupParameters) DeepCopy() *PortGroupParameters {
	if in == nil {
		return nil
	}
	out := new(PortGroupParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortGroupSpec) DeepCopyInto(out *PortGroupSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortGroupSpec.
func (in *PortGroupSpec) DeepCopy() *PortGroupSpec {
	if in == nil {
		return nil
	}
	out := new(PortGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortGroupStatus) DeepCopyInto(out *PortGroupStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortGroupStatus.
func (in *PortGroupStatus) DeepCopy() *PortGroupStatus {
	if in == nil {
		return nil
	}
	out := new(PortGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VlanRangeObservation) DeepCopyInto(out *VlanRangeObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VlanRangeObservation.
func (in *VlanRangeObservation) DeepCopy() *VlanRangeObservation {
	if in == nil {
		return nil
	}
	out := new(VlanRangeObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VlanRangeParameters) DeepCopyInto(out *VlanRangeParameters) {
	*out = *in
	if in.MaxVlan != nil {
		in, out := &in.MaxVlan, &out.MaxVlan
		*out = new(float64)
		**out = **in
	}
	if in.MinVlan != nil {
		in, out := &in.MinVlan, &out.MinVlan
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VlanRangeParameters.
func (in *VlanRangeParameters) DeepCopy() *VlanRangeParameters {
	if in == nil {
		return nil
	}
	out := new(VlanRangeParameters)
	in.DeepCopyInto(out)
	return out
}
