//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualSwitch) DeepCopyInto(out *VirtualSwitch) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualSwitch.
func (in *VirtualSwitch) DeepCopy() *VirtualSwitch {
	if in == nil {
		return nil
	}
	out := new(VirtualSwitch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualSwitch) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualSwitchList) DeepCopyInto(out *VirtualSwitchList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirtualSwitch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualSwitchList.
func (in *VirtualSwitchList) DeepCopy() *VirtualSwitchList {
	if in == nil {
		return nil
	}
	out := new(VirtualSwitchList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualSwitchList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualSwitchObservation) DeepCopyInto(out *VirtualSwitchObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualSwitchObservation.
func (in *VirtualSwitchObservation) DeepCopy() *VirtualSwitchObservation {
	if in == nil {
		return nil
	}
	out := new(VirtualSwitchObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualSwitchParameters) DeepCopyInto(out *VirtualSwitchParameters) {
	*out = *in
	if in.ActiveNics != nil {
		in, out := &in.ActiveNics, &out.ActiveNics
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.AllowForgedTransmits != nil {
		in, out := &in.AllowForgedTransmits, &out.AllowForgedTransmits
		*out = new(bool)
		**out = **in
	}
	if in.AllowMacChanges != nil {
		in, out := &in.AllowMacChanges, &out.AllowMacChanges
		*out = new(bool)
		**out = **in
	}
	if in.AllowPromiscuous != nil {
		in, out := &in.AllowPromiscuous, &out.AllowPromiscuous
		*out = new(bool)
		**out = **in
	}
	if in.BeaconInterval != nil {
		in, out := &in.BeaconInterval, &out.BeaconInterval
		*out = new(float64)
		**out = **in
	}
	if in.CheckBeacon != nil {
		in, out := &in.CheckBeacon, &out.CheckBeacon
		*out = new(bool)
		**out = **in
	}
	if in.Failback != nil {
		in, out := &in.Failback, &out.Failback
		*out = new(bool)
		**out = **in
	}
	if in.HostSystemID != nil {
		in, out := &in.HostSystemID, &out.HostSystemID
		*out = new(string)
		**out = **in
	}
	if in.LinkDiscoveryOperation != nil {
		in, out := &in.LinkDiscoveryOperation, &out.LinkDiscoveryOperation
		*out = new(string)
		**out = **in
	}
	if in.LinkDiscoveryProtocol != nil {
		in, out := &in.LinkDiscoveryProtocol, &out.LinkDiscoveryProtocol
		*out = new(string)
		**out = **in
	}
	if in.Mtu != nil {
		in, out := &in.Mtu, &out.Mtu
		*out = new(float64)
		**out = **in
	}
	if in.NetworkAdapters != nil {
		in, out := &in.NetworkAdapters, &out.NetworkAdapters
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.NotifySwitches != nil {
		in, out := &in.NotifySwitches, &out.NotifySwitches
		*out = new(bool)
		**out = **in
	}
	if in.NumberOfPorts != nil {
		in, out := &in.NumberOfPorts, &out.NumberOfPorts
		*out = new(float64)
		**out = **in
	}
	if in.ShapingAverageBandwidth != nil {
		in, out := &in.ShapingAverageBandwidth, &out.ShapingAverageBandwidth
		*out = new(float64)
		**out = **in
	}
	if in.ShapingBurstSize != nil {
		in, out := &in.ShapingBurstSize, &out.ShapingBurstSize
		*out = new(float64)
		**out = **in
	}
	if in.ShapingEnabled != nil {
		in, out := &in.ShapingEnabled, &out.ShapingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ShapingPeakBandwidth != nil {
		in, out := &in.ShapingPeakBandwidth, &out.ShapingPeakBandwidth
		*out = new(float64)
		**out = **in
	}
	if in.StandbyNics != nil {
		in, out := &in.StandbyNics, &out.StandbyNics
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.TeamingPolicy != nil {
		in, out := &in.TeamingPolicy, &out.TeamingPolicy
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualSwitchParameters.
func (in *VirtualSwitchParameters) DeepCopy() *VirtualSwitchParameters {
	if in == nil {
		return nil
	}
	out := new(VirtualSwitchParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualSwitchSpec) DeepCopyInto(out *VirtualSwitchSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualSwitchSpec.
func (in *VirtualSwitchSpec) DeepCopy() *VirtualSwitchSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualSwitchSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualSwitchStatus) DeepCopyInto(out *VirtualSwitchStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualSwitchStatus.
func (in *VirtualSwitchStatus) DeepCopy() *VirtualSwitchStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualSwitchStatus)
	in.DeepCopyInto(out)
	return out
}
