apiVersion: vspherevirtualmachine.vsphere.jet.crossplane.io/v1alpha1
kind: Machine
metadata:
  name: hello-crossplane-vm
spec:
  forProvider:
    resourcePoolId: "resgroup-16"
    datastoreId: "datastore-11"
    numCpus: 2
    memory: 1024
    guestId: "other3xLinux64Guest"
    networkInterface:
    - networkId: "network-12"
    disk:
    - label: "disk0"
      size: 20
  providerConfigRef:
    name: default